source "https://rubygems.org"

gem 'cucumber'
gem 'capybara'
gem 'rspec'
gem 'selenium-webdriver'
gem 'poltergeist'
gem 'phantomjs'
gem 'pry-byebug'
gem 'settingslogic', '~> 2.0.9'
gem 'faker'
gem 'httparty'
gem 'chromedriver-helper'
gem 'site_prism'